#!/usr/bin/php
<?php

require('settings.inc.php');
require('miner.inc.php');


/*
CREATE TABLE [pools] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[When] INTEGER DEFAULT '0' NULL,
[Description] TEXT  NULL,
[PoolID] INTEGER  NULL,
[Url] TEXT  NULL,
[Status] VARCHAR(64)  NULL,
[Priority] INTEGER DEFAULT '0' NULL,
[Quota] INTEGER DEFAULT '0' NULL,
[LongPoll] VARCHAR(16)  NULL,
[Getworks] INTEGER DEFAULT '0' NULL,
[Accepted] INTEGER DEFAULT '0' NULL,
[Rejected] INTEGER DEFAULT '0' NULL,
[Works] INTEGER DEFAULT '0' NULL,
[Discarded] INTEGER DEFAULT '0' NULL,
[Stale] INTEGER DEFAULT '0' NULL,
[GetFailures] INTEGER DEFAULT '0' NULL,
[RemoteFailures] INTEGER DEFAULT '0' NULL,
[User] VARCHAR(128)  NULL,
[LastShareTime] INTEGER DEFAULT '0' NULL,
[Diff1Shares] INTEGER DEFAULT '0' NULL,
[ProxyType] VARCHAR(64)  NULL,
[Proxy] VARCHAR(128)  NULL,
[DifficultyAccepted] INTEGER DEFAULT '0' NULL,
[DifficultyRejected] INTEGER DEFAULT '0' NULL,
[DifficultyStale] INTEGER DEFAULT '0' NULL,
[LastShareDifficulty] INTEGER DEFAULT '0' NULL,
[HasStratum] INTEGER DEFAULT '0' NULL,
[StratumActive] INTEGER DEFAULT '0' NULL,
[StratumURL] VARCHAR(128)  NULL,
[HasGBT] INTEGER DEFAULT '0' NULL,
[BestShare] INTEGER DEFAULT '0' NULL,
[PoolRejected] REAL DEFAULT '0' NULL,
[PoolStale] REAL DEFAULT '0' NULL,
[create_date] TIMESTAMP  NULL
)
*/
$datetime = date("Y-m-d H:i:s");
$db = new PDO('sqlite:/opt/minepeon/var/sql/pools.db');
$result = cgminer("pools", "");
$when = @$result['STATUS'][0]['When'];
$description = @$result['STATUS'][0]['Description'];
foreach ($result['POOLS'] as $pool) {
  $query = 'INSERT INTO "pools" ("When","Description","PoolID","Url","Status", "Priority", "Quota", "LongPoll", "Getworks", "Accepted", "Rejected", "Works", "Discarded", "Stale", "GetFailures", "RemoteFailures", "User", "LastShareTime", "Diff1Shares", "ProxyType", "Proxy", "DifficultyAccepted", "DifficultyRejected", "DifficultyStale", "LastShareDifficulty", "HasStratum", "StratumActive", "StratumURL", "HasGBT", "BestShare", "PoolRejected", "PoolStale","create_date") 
    VALUES ("' .
    $when. '", "' .
    $description. '", "' .
    $pool["POOL"] . '", "' .
    $pool["URL"] . '", "' .
    $pool["Status"] . '", "' .
    $pool["Priority"] . '", "' .
    $pool["Quota"] . '", "' .
    $pool["LongPoll"] . '", "' .
    $pool["Getworks"] . '", "' .
    $pool["Accepted"] . '", "' .
    $pool["Rejected"] . '", "' .
    $pool["Works"] . '", "' .
    $pool["Discarded"] . '", "' .
    $pool["Stale"] . '", "' .
    $pool["GetFailures"] . '", "' .
    $pool["RemoteFailures"] . '", "' .
    $pool["User"] . '", "' .
    $pool["LastShareTime"] . '", "' .
    $pool["Diff1Shares"] . '", "' .
    $pool["ProxyType"] . '", "' .
    $pool["Proxy"] . '", "' .
    $pool["DifficultyAccepted"] . '", "' .
    $pool["DifficultyRejected"] . '", "' .
    $pool["DifficultyStale"] . '", "' .
    $pool["LastShareDifficulty"] . '", "' .
    $pool["HasStratum"] . '", "' .
    $pool["StratumActive"] . '", "' .
    $pool["StratumURL"] . '", "' .
    $pool["HasGBT"] . '", "' .
    $pool["BestShare"] . '", "' .
    $pool["PoolRejected%"] . '", "' .
    $pool["PoolStale%"] . '", "' .
    $datetime . '")';

    $db->exec($query);
}

?>
